# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'upload.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(821, 517)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 40, 311, 420))
        self.label.setStyleSheet("border-image: url(:/images/static/image/1.png);\n"
"background-color: rgba(0, 0, 0, 0.5);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(349, 40, 401, 420))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-right-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.uploadButton = QtWidgets.QPushButton(Form)
        self.uploadButton.setGeometry(QtCore.QRect(490, 390, 231, 51))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(13)
        self.uploadButton.setFont(font)
        self.uploadButton.setStyleSheet("#uploadButton {\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"    color:  rgb(0, 0, 0);\n"
"    border:3px solid rgb(239, 239, 239);\n"
"    border-radius:8px;\n"
"}\n"
"#uploadButton:hover {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"#uploadButton:pressed {\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"\n"
"}")
        self.uploadButton.setObjectName("uploadButton")
        self.closeButton = QtWidgets.QPushButton(Form)
        self.closeButton.setGeometry(QtCore.QRect(690, 50, 41, 31))
        self.closeButton.setStyleSheet("#close {\n"
"    border:none;\n"
"}\n"
"#close:hover {\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.closeButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/static/icon/close.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon)
        self.closeButton.setObjectName("closeButton")
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setGeometry(QtCore.QRect(420, 90, 251, 81))
        font = QtGui.QFont()
        font.setFamily("华文中宋")
        font.setPointSize(15)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("border:none;")
        self.textBrowser.setObjectName("textBrowser")
        self.name = QtWidgets.QLineEdit(Form)
        self.name.setGeometry(QtCore.QRect(80, 100, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.name.setFont(font)
        self.name.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.name.setObjectName("name")
        self.gender = QtWidgets.QLineEdit(Form)
        self.gender.setGeometry(QtCore.QRect(80, 170, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gender.setFont(font)
        self.gender.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.gender.setObjectName("gender")
        self.age = QtWidgets.QLineEdit(Form)
        self.age.setGeometry(QtCore.QRect(80, 240, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.age.setFont(font)
        self.age.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.age.setObjectName("age")
        self.bloodType = QtWidgets.QLineEdit(Form)
        self.bloodType.setGeometry(QtCore.QRect(80, 310, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bloodType.setFont(font)
        self.bloodType.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.bloodType.setObjectName("bloodType")
        self.medicine = QtWidgets.QLineEdit(Form)
        self.medicine.setGeometry(QtCore.QRect(80, 380, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.medicine.setFont(font)
        self.medicine.setStyleSheet("border:1px solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.medicine.setObjectName("medicine")
        self.code = QtWidgets.QLabel(Form)
        self.code.setGeometry(QtCore.QRect(380, 201, 341, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.code.setFont(font)
        self.code.setText("")
        self.code.setObjectName("code")
        self.codeType = QtWidgets.QComboBox(Form)
        self.codeType.setGeometry(QtCore.QRect(360, 400, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.codeType.setFont(font)
        self.codeType.setStyleSheet("#codeType {\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"    color:  rgb(0, 0, 0);\n"
"    border:3px solid rgb(239, 239, 239);\n"
"    border-radius:8px;\n"
"}\n"
"#codeType:hover {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    color:  rgb(0, 0, 0);\n"
"}\n"
"#codeType:pressed {\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"\n"
"}")
        self.codeType.setEditable(True)
        self.codeType.setObjectName("codeType")
        self.codeType.addItem("")
        self.codeType.addItem("")
        self.back = QtWidgets.QPushButton(Form)
        self.back.setGeometry(QtCore.QRect(360, 50, 41, 31))
        self.back.setStyleSheet("#back {\n"
"    border:none;\n"
"}\n"
"#back:hover {\n"
"    \n"
"    background-color: rgb(239, 239, 239);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.back.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/static/icon/back.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back.setIcon(icon1)
        self.back.setObjectName("back")

        self.retranslateUi(Form)
        self.closeButton.clicked.connect(Form.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.uploadButton.setText(_translate("Form", "Upload"))
        self.textBrowser.setHtml(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'华文中宋\'; font-size:15pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:600;\">       智能医疗</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'SimSun\'; font-size:14pt; font-weight:600;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'SimSun\'; font-size:14pt; font-weight:600;\">病人条形码标识与管理系统</span></p></body></html>"))
        self.name.setPlaceholderText(_translate("Form", "Name："))
        self.gender.setPlaceholderText(_translate("Form", "Gender："))
        self.age.setPlaceholderText(_translate("Form", "Age："))
        self.bloodType.setPlaceholderText(_translate("Form", "Blood Type："))
        self.medicine.setPlaceholderText(_translate("Form", "Medicine："))
        self.codeType.setPlaceholderText(_translate("Form", "编码格式"))
        self.codeType.setItemText(0, _translate("Form", "code128"))
        self.codeType.setItemText(1, _translate("Form", "gs1_128"))
import ui.resource_rc
